### ISSUE TITLE
http://www.ennerchi.com/projects/jrails is down

### ISSUE THREAD

**Issue by scudco** [aaronchi/jrails#12]
http://www.ennerchi.com/projects/jrails is showing a GoDaddy placeholder page :(

**Comment by gravis** [comment]
same as #7 
:)

**Comment by scudco** [comment]
d'oh. wow it has been a while. does he need someone to pony up for a domain renewal? I'm sure we could all do that for him :]

**Comment by konung** [comment]
I have a question related to this. Is jrails dead?  As in the last commit is from november, site is down, and google groups  is full of spam. Anyone any idea?

**Comment by levifig** [comment]
I'll second that question and add that jRails is totally unnecessary in Rails 3 as it's now JS framework-agnostic (via the unobtrusive JS effort). Check more info here: http://github.com/rails/jquery-ujs

RIP jRails. We most certainly love and miss you.

**Comment by konung** [comment]
That's true, but Rails3 is not stable yet, and there are A LOT OF rails 2 apps out there.

**Comment by levifig** [comment]
@konung Not sure where you got the idea that Rails 3 is not stable yet… It's still in beta but it's stable.

Has to Rails 2 apps out there, they can still use jQuery like they have been in the past, but can't update! That's the normal procedure on deprecated software: it works, but can't upgrade. :)

**Comment by konung** [comment]
levifig - beta means "not ready for production, not stable, and while no new features may be added, there are still a lot of  potentially api-breaking bug fixes" in my book. They are at the 3rd beta already, maybe one-two more, then a couple of RCs, than stable. Now I'm not criticizing  - they are doing a great job, and the more testing they do the better, but until it's stable it ain't stable, it's beta.  And I'm not being picky, but I'm following a couple of gems that are trying to get Rails3 ready and they keep needing to change their code, cause Rail3 is being fixed, which is a totally normal process, but  which in turn means that if I were to use Rails 3 for anything other than a basic site, but something that actually uses a few gems and plugins, I would be constantly fixing my  site until Rails 3 is stable, and most of the gems get stable. So until it is, it ain't. :-)

**Comment by levifig** [comment]
@konung Fair enough… I wondered about jRails a while back as well and just considered it dead and buried (way before Rails 3 came along). I just went on to include jQuery from source and just do jQuery stuff (not ideal)… :(

Let's hope this ain't dead though… :S

**Comment by konung** [comment]
Same thing here. Which means no rjs stuff. Which may be a good thing....
