### ISSUE TITLE
Rake deprecation warning for Rails 2.3.8

### ISSUE THREAD

**Issue by jocubeit** [aaronchi/jrails#13]
DEPRECATION WARNING: Rake tasks in vendor/plugins/jrails/tasks are deprecated.

Use lib/tasks instead. (called from /.rvm/gems/ruby-1.8.7-p249/gems/rails-2.3.8/lib/tasks/rails.rb:10)

**Comment by jalvarezsamayoa** [comment]
Does this have a solution yet? Any recomendations?

**Comment by jocubeit** [comment]
I don't believe this project is being actively monitored or worked on anymore.

Having said that, it's only a deprecation warning so it doesn't actually affect the runtime performance. If you dislike deprecation warnings you can manually move the tasks folder (with contents) into the lib directory. Then amend any references to the tasks location in places like the s.files array variable in the gemspec. I think you will also need to fix any relative paths in the rake task itself (scripts variable) because I believe they are relative to jrails.rake file itself.

**Comment by benoror** [comment]
Maybe some fork have fixed this?

**Comment by mhoyer** [comment]
@benoror Quick and simple, but you'll find the fix in this fork: https://github.com/mhoyer/jrails

**Comment by jocubeit** [comment]
Well done Marcel, I probably should've done this myself, I've been using my modified version for 8 months.

**Comment by jocubeit** [comment]
May as well close this issue now.
