### ISSUE TITLE
Could you please update jQuery libs please ?

### ISSUE THREAD

**Issue by gravis** [aaronchi/jrails#2]
Everything's in the title :)
I've noticed the jQuery UI bundled in a 1.6rc5 (I guess, I've seen that in the pack version). The current stable version is 1.7.1.

Thanks !

**Comment by gravis** [comment]
someone here ?

**Comment by aaronchi** [comment]
Done... You can replace this with a custom version of jquery-ui without any ill effect. Will update readme later.
