### ISSUE TITLE
Compatibility issue with ruby1.9

### ISSUE THREAD

**Issue by gravis** [aaronchi/jrails#3]
Hi,

jrails is not compatible with ruby1.9, I think it should be :)

Here's the output I get :

@@@
uninitialized constant ActionView::Helpers::JavaScriptElementProxy::ActionView
/opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:105:in `rescue in const_missing'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:94:in`const_missing'
/yyy/vendor/plugins/jrails/lib/jrails.rb:229:in `<class:JavaScriptElementProxy>'
/yyy/vendor/plugins/jrails/lib/jrails.rb:226:in`module:Helpers'
/yyy/vendor/plugins/jrails/lib/jrails.rb:2:in `<module:ActionView>'
/yyy/vendor/plugins/jrails/lib/jrails.rb:1:in`<top (required)>'
@@@

**Comment by aaronchi** [comment]
Should be fixed now

**Comment by gravis** [comment]
Thanks a lot, It's important since your repo is the reference :)

**Comment by gravis** [comment]
works like a charm. Thank you very much.
