### ISSUE TITLE
RDocs

### ISSUE THREAD

**Issue by zquestz** [aaronchi/jrails#4]
Having an issue generating rdocs... is there a fix/workaround?

questmbp:asset-manager quest$ rake doc:plugins
rdoc -o doc/plugins/jrails --title 'Jrails Plugin Documentation' --line-numbers --inline-source --charset utf-8 -T html vendor/plugins/jrails/lib/jrails.rb vendor/plugins/jrails/CHANGELOG
--inline-source will be removed from RDoc on or after August 2009
Parsing sources with 2 thread(s)...
100% [ 2/ 2]  vendor/plugins/jrails/CHANGELOG                                   

Generating Darkfish...
uh-oh! RDoc had a problem:
could not find template "html"

run with --debug for full backtrace
rake aborted!
Command failed with status (1): [rdoc -o doc/plugins/jrails --title 'Jrails...]

(See full trace by running task with --trace)

**Comment by zquestz** [comment]
Ohh, and I have the following rdoc gems installed.

rdoc (2.4.3, 2.3.0)
rdoc_chm (2.4.2)
rdoc_html_templates (2.3.0)

**Comment by hyfather** [comment]
I know rdoc.gem v2.1.0 has the 'html' template in lib/rdoc/generator/template.  
Try rolling back?
